### ISSUE TITLE
Don't depend on vst-rs if possible

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/reaper-rs#14]
Right now reaper-low depends on vst-rs for being able to provide easy integration with VST plug-ins. However, because there doesn't seem to exist anything like peer dependencies in Rust, this creates a problem if someone wants to use another version of vst-rs.

https://github.com/rust-lang/rust/issues/44663 could solve this in future. But for now, maybe there's a way to use a more generic, opaque approach which doesn't require vst-rs at all.

**Comment by helgoboss** [comment]
A more generic variant of this issue is #20.

**Comment by Boscop** [comment]
Currently, reaper-rs depends on `vst = { git = "https://github.com/helgoboss/vst-rs", branch = "feature/custom-support-variant" }`.
In my VST, I had [this issue](https://github.com/RustAudio/vst-rs/issues/131) which was fixed in 0.2.1, but your fork doesn't have that fix yet..
Since your `can_do` PR was merged into upstream, you could just depend on `vst = "*"` in Cargo.toml, so it will always use the version that the downstream crate uses.
I think this would be the most practical way to fix this issue. (Until you find a way to not depend on vst-rs at all.)

**Comment by helgoboss** [comment]
Ah, good suggestion. I was not even sure what the `*` means in this context. Will do that soon.

**Comment by Boscop** [comment]
Could you please prioritize this? :)
Currently, my VST that uses `reaper-rs` cannot use `SendEventBuffer` because of https://github.com/RustAudio/vst-rs/issues/131 which was fixed upstream.

**Comment by helgoboss** [comment]
It's already changed. Sorry, I forgot to close the issue.
