### ISSUE TITLE
Where to Help?

### ISSUE THREAD

**Issue by PrismaPhonic** [helgoboss/reaper-rs#18]
Hi!

I just came across your library when I thought to myself, "Oh man, if no one has created a Rust Bindings library for the Reaper API, that would be a great project!"

It's nice to see that not only is this already a project, but a very well documented and nicely written one! I would love to contribute. I see that there are still roughly 700 functions to support in the medium level API.

Are you looking for help, and if so, what's the best practice here for me to help out without doing overlapping work? Can we put chunks of functions into assignable issues so it's obvious who's working on which functions?

**Comment by helgoboss** [comment]
@PrismaPhonic Thank you! Yes, I'm looking for help. I would love if this turns into a collaborative project and I'm glad that someone is interested.

Filling the gap of missing medium-level API functions is at the moment probably the easiest way to divide and conquer. The way I approached this so far was to implement exactly the functions which I need (for porting the ReaLearn plug-in). This has the benefit that the function is put to use immediately and any deficiency in design or functionality can be detected very early. For the next months, my plan is _not_ to add much more functions to the medium-level API. I rather want to concentrate on the high-level API. So if you have any functions that you want to see in reaper-medium, feel free to give it a go :) You could create a draft PR for a single function you want to implement, or a set of functions, if this is too fine-grained.

Apart from that, there are still some "TODO" markers in reaper-low and reaper-medium (and lots of in reaper-high, but I think this is not ready yet for contribution). I could revise them and convert them into GitHub issues.

Let me know if there's anything you need to get started.

**Comment by GavinRay97** [comment]
I would also be interested in helping out if possible =)
(Probably low-hanging fruit/easier tasks since my Rust skills are still fledgling)

Is there a pattern I could use for identifying which functions from `reaper-low` have not yet been wrapped in `reaper-medium`?

I've tried to look through the source but think I'm not familiar enough with project's architecture.

**Comment by helgoboss** [comment]
At the moment the easiest algorithm is to just pick one randomly and check that it's not yet in `reaper-medium` :) Low-levelAPI: PascalCase, medium-level API: snake_case.

**Comment by GavinRay97** [comment]
Awesome =D
Before I go off and try to do a bunch of these, do I have the general idea?

```h
#if defined(REAPERAPI_WANT_GetTrackFromPoint) || !defined(REAPERAPI_MINIMAL)
REAPERAPI_DEF //==============================================
// GetTrackFromPoint
// Returns the track from the screen coordinates specified. If the screen coordinates refer to a window associated to the track (such as FX), the track will be returned. infoOutOptional will be set to 1 if it is likely an envelope, 2 if it is likely a track FX.

  MediaTrack* (*GetTrackFromPoint)(int screen_x, int screen_y, int* infoOutOptional);
#endif
```

```rust
#[measure(ResponseTimeSingleThreaded)]
pub unsafe fn get_track_from_point(
    &self,
    track: MediaTrack,
    x: i32,
    y: i32,
) -> ReaperFunctionResult<MediaTrack>
where
    UsageScope: MainThreadOnly,
{
    self.require_main_thread();
    let ptr = self.low.GetTrackFromPoint(x, y, info_out = null_mut()) as *mut raw::MediaTrack;
    NonNull::new(ptr).ok_or_else(|| {
        ReaperFunctionError::new("couldn't get track at coordinates {}, {}".fmt(x, y))
    })
}
```

**Comment by helgoboss** [comment]
The basics yes :) There's something to say though:

- The original function doesn't take a track as parameter.
- The return type should be an `Option` rather than a `Result` because "There's no track at these coordinates!" conceptually is a perfectly valid result, not an error.
- The original function has an out parameter. In medium-level API we don't want out parameters because they are so ugly to use, so we should make this part of the return value. It should be an enum defined in `misc_enums.rs` to free the user from wondering what the hell is 1 and 2 supposed to mean ;) In order to return both the media track and the enum variant, we could return a tuple but that wouldn't be in line with what I've done so far. Whever there are more values to be returned, I added a `*MethodName*Result` struct with just public fields, see for example `enum_projects()`.
- I tried wherever possible to restrict the number types in order to make the API more self-documenting. E.g. I'm not sure if negative values for x or y would make sense in this case or if `u32` would be the better type here. That's sometimes hard to find out and requires experimentation or asking Justin. On the other hand, restricting the types is not always good. If at some point, the REAPER devs give those negative values a special meaning, one has to cope with backward compatibility.
- Rust doesn't support named arguments.

**Comment by GavinRay97** [comment]
> The original function doesn't take a track as parameter.

D'oh 🤦 

> The return type should be an Option rather than a Result because "There's no track at these coordinates!" conceptually is a perfectly valid result, not an error.

Got it 👍 

> The original function has an out parameter. In medium-level API we don't want out parameters because they are so ugly to use, so we should make this part of the return value. It should be an enum defined in misc_enums.rs to free the user from wondering what the hell is 1 and 2 supposed to mean ;) In order to return both the media track and the enum variant, we could return a tuple but that wouldn't be in line with what I've done so far. Whever there are more values to be returned, I added a *MethodName*Result struct with just public fields, see for example enum_projects().

Was able to follow the example here, think I got it.

> I tried wherever possible to restrict the number types in order to make the API more self-documenting. E.g. I'm not sure if negative values for x or y would make sense in this case or if u32 would be the better type here. That's sometimes hard to find out and requires experimentation or asking Justin. On the other hand, restricting the types is not always good. If at some point, the REAPER devs give those negative values a special meaning, one has to cope with backward compatibility.

Hmm yeah could be, though negative coordinates would definitely be a weird one. I can see the logic in backwards compatibility though.

> Rust doesn't support named arguments.

Also d'oh. Weird that Rust Analyzer didn't catch that though. I also seem to be able to return blatantly wrong types in functions without it giving errors. Need to look into that.

-----------------

I think this should do it? Not sure if the `match Some/Err` is considered idiomatic.

```rust
pub enum GetTrackFromPointResultAdditionalInfo {
    Envelope,
    TrackFX,
}

impl GetTrackFromPointResultAdditionalInfo {
    /// Converts this value to an integer as expected by the low-level API.
    pub fn to_raw(self) -> i32 {
        use GetTrackFromPointResultAdditionalInfo::*;
        match self {
            Envelope => 1,
            TrackFX => 2,
        }
    }
}
```

```rust
#[derive(Clone, PartialEq, Hash, Debug)]
pub struct GetTrackFromPointResult {
    pub track: MediaTrack,
    pub additional_info: GetTrackFromPointResultAdditionalInfo,
}

/// Returns the track from the screen coordinates specified.
///
/// If the screen coordinates refer to a window associated to the track (such as FX), the track
/// will be returned. infoOutOptional will be set to 1 if it is likely an envelope, 2 if it
/// is likely a track FX.
#[measure(ResponseTimeSingleThreaded)]
pub unsafe fn get_track_from_point(&self, x: u32, y: u32) -> Option<GetTrackFromPointResult>
where
    UsageScope: MainThreadOnly,
{
    self.require_main_thread();

    let info_out = null_mut();
    let ptr = self.low.GetTrackFromPoint(x, y, info_out) as *mut raw::MediaTrack;
    let media_track = NonNull::new(ptr).ok_or_else(|| {
        ReaperFunctionError::new("couldn't get track at coordinates {}, {}".fmt(x, y))
    });

    match media_track {
        Some(value) => Some(GetTrackFromPointResult {
            track: media_track,
            additional_info: info_out,
        }),
        Err(err) => Err(err),
    }
}
```
